### PR TITLE
New Icons with source.

### PR DESCRIPTION
**Pull request by josephfusco**
As per discussion in PR #319

### CODE REVIEW

**Comment by josephfusco** [comment]
@cstigler I also sent in a PR to update the site. See https://github.com/SelfControlApp/selfcontrolapp.github.io/pull/1

Also here is the final agreed upon icon to update the GitHub org image when the time comes :+1:
icon

**Comment by cstigler** [comment]
Looks great. Thanks so much for putting this together!

**Comment by josephfusco** [comment]
Thanks :). Np.

**Comment by mikecrittenden** [comment]
:+1: Just got the update and it looks fabulous!

**Pull request merged**
