### PR TITLE
Changed whitelist/blacklist to allowlist/blocklist in entire codebase

### PR DESCRIPTION
**Pull request by raviriley**
I fixed it for almost all occurrences. I split the changes into 2 commits, one for text or strings files and the other for `.m` files. I didn't rename `WhitelistScraper.h` as its contents are the same as `AllowlistScraper.h`.

### CODE REVIEW

**Comment by raviriley** [comment]
Please add the label `hacktoberfest-accepted` to my PR if accepted, I'm participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/) :)

**Comment by cstigler** [comment]
Hi @raviriley, first thanks so much for taking the time to contribute!

I gather that you wanted to make the blacklist --> blocklist transition consistent throughout the code. However, I left most of these references unchanged intentionally for , you can see the [GitHub comment I made on the original issue](https://github.com/SelfControlApp/selfcontrol/issues/624#issuecomment-647217466) which explains why I left them unchanged. Restated, I don't want to change the variable names (ex `HostBlacklist`or `BlockAsWhitelist`) for backwards-compatibility reasons, and I don't want to change non-English localizations since I don't want to presume and someone from each region can determine what's culturally appropriate for them.

I do think you might have caught one or two other instances where it could be changed (ex: I saw the README in there). But it might end up just being a line or two, so not sure if you want to slim down this PR to just hit those!

**Comment by raviriley** [comment]
Got it, will do! Sorry about that!

**Comment by raviriley** [comment]
@cstigler Fixed

**Pull request merged**
