### PR TITLE
MASPreferences Update

### PR DESCRIPTION
**Pull request by nakulbajaj**
More interesting and cool PRs coming soon.

### CODE REVIEW

**Comment by nakulbajaj** [comment]
Also was wondering why it's necessary to specify a version for each pod rather than just letting `pod install` and `pod update` immediately retrieve the latest version. 

Thanks

**Comment by cstigler** [comment]
@nakulbajaj the problem is that if we don't pin versions, we can't guarantee that I am running the same code that you are running - or even that I'm running the same code on one computer as I am on the other.

If the latest version of some pod introduces a bug or breaks something, it could easily slip through and into a live version. Pinning versions prevents this by giving me an assurance that you are running the same code in your tests that I run in my tests, and that production users will get that same code in the distribution build.

**Comment by cstigler** [comment]
This version bump looks good, merged!

**Comment by nakulbajaj** [comment]
Oh I see - that makes more sense. 


Thanks again!

**Pull request closed without merging**
