### PR TITLE
Update Icns.

### PR DESCRIPTION
**Pull request by josephfusco**
As mentioned a few times, the logo is kind of outdated by now. I picked a skull that looks less terrifying and appealing to click on. :skull: :smile: Let me know what you think. Of course this would still have to be packaged into a release.

icon

### CODE REVIEW

**Comment by korve** [comment]
I like it :+1:

**Comment by slambert** [comment]
Just wanted to say thanks for stepping up and creating something.

**Comment by slambert** [comment]
I found this one someone sent us from 2010. I prefer the one you did, @josephfusco 
 
[selfcontrol icons.zip](https://github.com/SelfControlApp/selfcontrol/files/74848/selfcontrol.icons.zip)

**Comment by josephfusco** [comment]
Well if we want to go ahead with this I can submit a PR for the website favicons and logo as well.

**Comment by josephfusco** [comment]
@slambert that one from 2010 is pretty good. :) I would reduce the drop-shadow a little though to match El Capitan standards :smile:

**Comment by cstigler** [comment]
@josephfusco awesome, thanks for making this! i like it. Attaching another icon that was sent to us over the years just to stir thoughts (I definitely prefer the draft you made) 512x512

**Comment by cstigler** [comment]
Only thing I'm still a little hesitant about: this drops the the ace of spades motif entirely. I don't know how common this is among users, but for me that's how I first identify it in my dock/app-switcher. This definitely looks significantly nicer than our current logo, but is a bit less distinctive to me

**Comment by josephfusco** [comment]
That one is real nice. I like the incorporation of a clock tick marks into the logo like that. I agree with what you are saying. It could be more unique (the one I made). Standby for another draft.

**Comment by cstigler** [comment]
One suggestion: we could change the circle back towards a spade shape, but fat/cartoony (not spindly like our current icon is at the bottom). If we did that, maybe we could even remove the crossbones and just enlarge the skull to emphasize it as our brand?

**Comment by josephfusco** [comment]
I like that idea as well. Will look less busy.

**Comment by cstigler** [comment]
I hope so! the thing I like most about your design is the simplicity: not too much going on, big lines, clean shapes. Whereas the current icon is little shades and lines everywhere - it's literally a photograph =)

**Comment by josephfusco** [comment]
icon

**Comment by josephfusco** [comment]
Looks like I went too light on the gradient. Can darken if you think.

**Comment by cstigler** [comment]
I love it! Looks great. I think you might be right on darkening the gradient a bit. And maybe the skull could get a little larger since there's a good bit of room? This is :fire:

**Comment by cstigler** [comment]
What does everybody else on this thread think? I'm all in favor of putting this in the next update, maybe after a bit more tweaking. It's a big upgrade!

**Comment by josephfusco** [comment]
Like that? icon

**Comment by josephfusco** [comment]
Or something a little more 3d ish like those other designs. Just throwing some more options out there. icon2

**Comment by cstigler** [comment]
Yes!! I like them both, but the 3D one especially really pops. A few more suggestions: the skull looks a little off-center towards the bottom (more space on top than bottom), we could try pushing it up? Also, what do you think about sharpening the point on top a tiny bit?

**Comment by cstigler** [comment]
Also, good point on the white border helping it stay visible - I know that's been a frequent complaint with our current icon

**Comment by cstigler** [comment]
👌 beautiful!
Le mer. 30 déc. 2015 à 7:43 PM, Joseph Fusco <notifications@github.com> a
écrit :

**Comment by josephfusco** [comment]
OK so I just revised that again. I increased the white border by a lot because it looked real dinky in the dock against other icons. Here are screenshots with the badge and without.

screen shot 2015-12-30 at 11 06 44 pm
screen shot 2015-12-30 at 11 07 17 pm

**Comment by slambert** [comment]
I think this is great. I'll miss the rough, "improper" style - I liked 
that is seemed a little scary - but I'm ok to let that go. Thanks a lot 
for working on this... Steve

**Comment by cstigler** [comment]
Exactly what @slambert said - I'll miss the ripped photo look, but mainly for personal sentimental reasons. It's time for a change! I think it looks great now. Can you update the PR with the new icons? Then I can merge and we'll put it in the next release.

**Comment by josephfusco** [comment]
Yeah no prob. I'm actually gonna make a new pull request then since we don't need to track these.

**Comment by josephfusco** [comment]
See #320

**Comment by josephfusco** [comment]
Yeah I understand the sentiment part. This is a pretty old repository. Luckily the old icon will forever be tracked. :octocat:

**Pull request closed without merging**
