### PR TITLE
centers timer label on yosemite fix for #233

### PR DESCRIPTION
**Pull request by kdaker**
a quick fix for #233 . I was unable to test on 10.9 but it should be safe.

### CODE REVIEW

**Comment by imkevinxu** [comment]
Can this be merged yet?

**Comment by cstigler** [comment]
@imkevinxu sorry, I tend to get to these in batches since it's easier for me. Will probably have a chance to go through a batch in the next week or two

**Comment by cstigler** [comment]
@kdaker thanks for the fix! :+1:

**Comment by kdaker** [comment]
@cstigler no problem!

**Pull request merged**
